language: java
jdk: oraclejdk8
sudo: false
env:
  secure: "RydUnQHJKXbIthgzIx21F7+jjWVn9bxIdtEIX29cbDVtCwliJGH53+lMR6Dy58XBYmvr+fVyF9BMRFX+UHjQiPG0noHCBTEYw78f2IoT29+jaufeDlFlWpTdg22RMfBVQMS8Y6tncYmg1I1doYd6Yfy/CGK7Loq21hsQcmoROWbDhdMTXdSDEv9qDvANIdc9Nox7ifSVQE92RfeMRyXlftIn0KuoH/axHz5wLyAOdPCmp5qVXl7YlQQRWvNub2nGyB3uU3JaMDPpNOAUYhyWHad2C8+xm7jSfnmI8BRZUS/q+98VPfXLtBkCXpZdJHpXrm/ScF1YI77efXa6zbTcR7NSZss19O/RbQXhCQjFs1Rb5jvg5GXhQY1np8RYohvnSamimuPj8bUJ9BlaPc0q86Z0HPTflZAs9FM1sFwMO/kRu1U26QeIarN5d5ruh7ylvaKtX1i28Am0OuSK4lBCmsdgEuzOlJeNZFwaBPgb8DJeXGd8vZ+V6sx/qtv35Q+rkFhbsk3Q+HoYsUTyrw6ckleWlZGu1R/Rd2Vu7WvSaG+fDRYzG2TiUp6cPdRW5ybuUsdobd3f+hpTurn3XuUr/FObh6qlJ6aJ9jAT+0aThVjUfrwiZ4fptZpAF33VKZ48WulnNZQUZIl7nWSDakVKfoK6Lab/B2aVR54D1lgVD/A="
script:
  - mvn clean install sonar:sonar -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=${SOMEVAR}
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email:
    recipients:
    - andrzej.kotwicki@gft.com
    on_success: always
after_success:
- bash <(curl -s https://codecov.io/bash)
